### PR TITLE
Added custom objective function support.

### PR DESCRIPTION
**Pull request by aj-michael**
If no objective function is provided, the solver defaults to minimizing distance.

### CODE REVIEW

**Comment by aj-michael** [comment]
Closes #14

**Comment by aj-michael** [comment]
ok @danhanson , I think this is ready. The tests pass locally; Travis is just being slow today.

In stead of using eval/parse, I am using include_string. All of the power, none of the type safety :+1:

**Comment by aj-michael** [comment]
Test coverage just went from 83.5% to 1.802%..... lol

**Comment by aj-michael** [comment]
@robinsdm , Since I was talking to you via GroupMe about this, maybe you would be the better reviewer for it than Dan?

**Comment by robinsdm** [comment]
Looks good.

**Pull request merged**
