### PR TITLE
Just the basics.

### PR DESCRIPTION
**Pull request by aj-michael**
Opening this now to see if it triggers Travis.

EDIT: The system is now a functional echo server on port 2929.

### CODE REVIEW

**Comment by aj-michael** [comment]
Hmmm, Julia packages seem to be very tightly coupled to the git repo that you store them in. I suspect that I will need the package name to match the name of the Julia module.

**Comment by danhanson** [comment]
looks good! :cactus:

**Comment by aj-michael** [comment]
:moneybag:

**Comment by aj-michael** [comment]
This fixes #3

**Comment by aj-michael** [comment]
This closes #2

**Pull request merged**
