### PR TITLE
Topic/specification

### LINKED ISSUE #4: Formalize problem
* [x] Create problem description document
* [ ] Determine input specification
* [ ] Determine output specification

### PR DESCRIPTION
**Pull request by aj-michael**
These sample request and responses are modeled after a discussion between @danhanson and I.

This closes #4

### CODE REVIEW

**Comment by danhanson** [comment]
Well I wrote my code to parse the response as you provided it, my code still uses the same format  for the request it had earlier since that was already written, it looks like this
```
{"commodities":[{"capacity":2},{"capacity"1}],
 "vehicles":[{"capacity":3}],
 "startsToPickUps":     [[512,433]],
 "pickUpsToDropOffs":[[459,90],
                                     [365,366]],
 "pickUpsToPickUps":[[0,371],
                                   [355,0]],
 "dropOffsToDropOffs":[[0,481],
                                      [464,0]]
}
```
I think changing to your format for commodities is a simple matter of concatenating the matrices and adding a table for commodities that shows their end indices, but I am not sure what we should do with the vehicle starts since I never calculate distances to the vehicles

**Comment by aj-michael** [comment]
I'm not sure what your point is with that comment.

**Comment by aj-michael** [comment]
If you're saying that you don't have the distances from vehicles to each other, that is fine if there is a constraint that enforces that that route segment cannot be used.

E.G. You can give me 0 for the distance between two vehicle starting locations because we can enforce that no two vehicles are on the same route. I discussed this in the model document.

**Comment by aj-michael** [comment]
@danhanson  please add the time parameter to this.

**Pull request merged**
